name: Deploy JavaDoc

on:
  push:
    branches:
      - master
    paths:
      - NeuroEvolutionPlugins/src/**
      - NeuroEvolutionPlugins/pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Generate JavaDoc
      run: |
        cd NeuroEvolutionPlugins
        mvn javadoc:javadoc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        clear: true
        folder: NeuroEvolutionPlugins/target/site/apidocs
        target-folder: docs
