name: Tagged Release

on:
  push:
    tags:
      - "v*"
      
jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.tagname.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Verify with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Get tagname
      id: tagname
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
  publish:
    needs: verify
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: NeuroEvolutionDemo.jar
            asset_name: NeuroEvolutionDemo-Linux.jar
          - os: windows-latest
            artifact_name: NeuroEvolutionDemo.jar
            asset_name: NeuroEvolutionDemo-Win.jar
          - os: macos-latest
            artifact_name: NeuroEvolutionDemo.jar
            asset_name: NeuroEvolutionDemo-Mac.jar
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Generate Jar
      run: |
        mvn --batch-mode --update-snapshots clean install package
    - name: Upload Application
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: NeuroEvolutionDemo/target/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        prerelease: false
        overwrite: true
        tag: ${{ needs.verify.outputs.tagname }}
        release_name: ${{ needs.verify.outputs.tagname }}
        body: This release is an automatic build.