name: Tests

on: push
      
jobs:
  test:
    name: test project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots test